name: example
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  cloud_firestore: ^4.17.2
  flutter:
    sdk: flutter
  flutterfire_json_converters:
    path: ../
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1