name: flutterfire_json_converters
description: flutterfire_json_converters package supplies some useful json_converters for your FlutterFire apps.
version: 0.0.5
homepage: https://github.com/KosukeSaigusa/flutterfire-json-converters

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  cloud_firestore: ^4.8.4
  flutter:
    sdk: flutter
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
